# Generated by Django 5.1.4 on 2024-12-27 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0013_alter_fboard_btime_alter_ftime_ftime'),
        ('member', '0005_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='food',
        ),
        migrations.AddField(
            model_name='rating',
            name='fboard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='foodBoard.fboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='star',
            name='fboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_by', to='foodBoard.fboard'),
        ),
        migrations.AlterField(
            model_name='star',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_boards', to='member.member'),
        ),
    ]
