# Generated by Django 5.1.4 on 2024-12-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fBoard',
            fields=[
                ('bNo', models.AutoField(primary_key=True, serialize=False)),
                ('bLocation', models.CharField(max_length=1000)),
                ('bTitle', models.CharField(max_length=200)),
                ('bSubtitle', models.CharField(max_length=200)),
                ('bContent', models.TextField()),
                ('bFile1', models.ImageField(upload_to='fBoard')),
                ('bFile2', models.ImageField(null=True, upload_to='fBoard')),
                ('bFile3', models.ImageField(null=True, upload_to='fBoard')),
                ('bHit', models.IntegerField(default=0)),
                ('bLike', models.IntegerField(default=0)),
                ('bDate', models.DateTimeField(auto_now=True)),
                ('like_members', models.ManyToManyField(related_name='fboard_like_members', to='member.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fBoard_member', to='member.member')),
            ],
        ),
    ]
