# Generated by Django 5.1.3 on 2024-12-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0004_alter_fboard_btime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fboard',
            name='bLike',
        ),
        migrations.RemoveField(
            model_name='fboard',
            name='bTime',
        ),
    ]
