# Generated by Django 5.1.3 on 2024-12-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0005_remove_fboard_blike_remove_fboard_btime'),
        ('member', '0002_remove_star_star_star_fboard_star_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='fTime',
            fields=[
                ('fNo', models.AutoField(primary_key=True, serialize=False)),
                ('fTime', models.IntegerField(choices=[(120, '2시간 이상'), (60, '1시간 이상'), (30, '30분 이내'), (10, '10분 이내'), (0, '바로 입장'), (45, '30분~1시간')])),
                ('fDate', models.DateTimeField(auto_now=True)),
                ('fBoard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fTime_fBoard', to='foodBoard.fboard')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fTime_member', to='member.member')),
            ],
        ),
    ]
