# Generated by Django 5.1.3 on 2024-12-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0006_ftime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftime',
            name='fPeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ftime',
            name='fTime',
            field=models.IntegerField(choices=[(120, '2시간 이상'), (10, '10분 이내'), (30, '30분 이내'), (45, '30분~1시간'), (60, '1시간 이상'), (0, '바로 입장')]),
        ),
    ]
