# Generated by Django 5.1.3 on 2024-12-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0012_alter_fboard_btime'),
        ('foodBoard', '0014_alter_ftime_ftime'),
    ]

    operations = [
    ]
