# Generated by Django 5.1.3 on 2024-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0015_merge_0012_alter_fboard_btime_0014_alter_ftime_ftime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fboard',
            name='bTime',
        ),
        migrations.AlterField(
            model_name='ftime',
            name='fTime',
            field=models.IntegerField(choices=[(30, '30분 이내'), (45, '30분~1시간'), (0, '바로 입장'), (60, '1시간 이상'), (10, '10분 이내'), (120, '2시간 이상')]),
        ),
    ]
