# Generated by Django 5.1.3 on 2024-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0018_alter_ftime_ftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftime',
            name='fTime',
            field=models.IntegerField(choices=[(120, '2시간 이상'), (60, '1시간 이상'), (10, '10분 이내'), (30, '30분 이내'), (0, '바로 입장'), (45, '30분~1시간')]),
        ),
    ]
