# Generated by Django 5.1.4 on 2024-12-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0022_alter_ftime_ftime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fboard',
            name='bTime',
            field=models.IntegerField(choices=[(10, '10분 이내'), (30, '30분 이내'), (120, '2시간 이상'), (0, '바로 입장'), (60, '1시간 이상'), (45, '30분~1시간')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ftime',
            name='fTime',
            field=models.IntegerField(choices=[(10, '10분 이내'), (30, '30분 이내'), (120, '2시간 이상'), (0, '바로 입장'), (60, '1시간 이상'), (45, '30분~1시간')]),
        ),
    ]
