# Generated by Django 5.1.4 on 2024-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='bFile1',
            field=models.ImageField(upload_to='fBoard'),
        ),
    ]
