# Generated by Django 5.1.4 on 2024-12-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couNo', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
                ('used_from', models.DateTimeField()),
                ('used_to', models.DateTimeField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.attendance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
