# Generated by Django 5.1.3 on 2024-12-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('birth', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=0)),
                ('agree1', models.DateTimeField(auto_now=True, max_length=100)),
                ('agree2', models.DateTimeField(auto_now=True, max_length=100)),
                ('mdate', models.DateTimeField(auto_now=True, max_length=100)),
            ],
        ),
    ]
