# Generated by Django 5.1.3 on 2024-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cgroup',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='cindent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='cstep',
            field=models.IntegerField(default=0),
        ),
    ]
