# Generated by Django 5.1.3 on 2024-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_cgroup_comment_cindent_comment_cstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cgroup',
            field=models.IntegerField(default=0),
        ),
    ]
