# Generated by Django 5.1.4 on 2024-12-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0003_alter_fboard_btime'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='star',
        ),
        migrations.AddField(
            model_name='star',
            name='fboard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='starred_by', to='foodBoard.fboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='starred_boards', to='member.member'),
            preserve_default=False,
        ),
    ]
