# Generated by Django 5.1.3 on 2024-12-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0008_alter_fboard_btime'),
        ('member', '0004_star_fboard_remove_star_star_star_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='star',
        ),
        migrations.AddField(
            model_name='star',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='star_member', to='member.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='fboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_fboard', to='foodBoard.fboard'),
        ),
    ]
