# Generated by Django 5.1.3 on 2024-12-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_f',
            name='bHit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board_f',
            name='bLike',
            field=models.IntegerField(default=0),
        ),
    ]
