# Generated by Django 5.1.3 on 2024-12-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0003_rename_board_f_fboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='bFile',
            field=models.ImageField(null=True, upload_to='fBoard'),
        ),
    ]
