# Generated by Django 5.1.3 on 2024-12-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0004_alter_fboard_bfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fBoard',
        ),
    ]
