# Generated by Django 5.1.3 on 2024-12-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('birth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('point', models.IntegerField(default=0)),
                ('agree1', models.DateTimeField(auto_now=True)),
                ('agree2', models.DateTimeField(auto_now=True)),
                ('mDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
