# Generated by Django 5.1.3 on 2024-12-09 03:38

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='verification_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='verification_email',
            field=models.EmailField(default=datetime.datetime(2024, 12, 9, 3, 38, 48, 416620, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
    ]
