# Generated by Django 5.1.3 on 2024-12-12 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_delete_emailverification_member_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='addr',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='agree1',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='agree2',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
