# Generated by Django 5.1.3 on 2024-12-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('웨이팅', '웨이팅👥'), ('실시간공유', '실시간공유🗫'), ('추천맛집', '추천맛집😋'), ('사건사고', '사건사고😈'), ('감성카페', '감성카페☕'), ('생활/편의', '생활/편의🧼'), ('취미', '취미🎮'), ('기타', '기타🔍'), ('교통', '교통🚗'), ('풍경', '풍경🌴')], max_length=500),
        ),
    ]
