# Generated by Django 5.1.3 on 2024-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('교통', '교통🚗'), ('풍경', '풍경🌴'), ('기타', '기타🔍'), ('실시간공유', '실시간공유🗫'), ('취미', '취미🎮'), ('사건사고', '사건사고😈'), ('웨이팅', '웨이팅👥'), ('생활/편의', '생활/편의🧼'), ('감성카페', '감성카페☕'), ('추천맛집', '추천맛집😋')], max_length=500),
        ),
    ]
