# Generated by Django 5.1.4 on 2024-12-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('실시간공유', '실시간공유🗫'), ('감성카페', '감성카페☕'), ('추천맛집', '추천맛집😋'), ('교통', '교통🚗'), ('풍경', '풍경🌴'), ('기타', '기타🔍'), ('웨이팅', '웨이팅👥'), ('취미', '취미🎮'), ('생활/편의', '생활/편의🧼'), ('사건사고', '사건사고😈')], max_length=500),
        ),
    ]
