# Generated by Django 5.1.3 on 2025-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_code',
            field=models.IntegerField(default=0),
        ),
    ]
