# Generated by Django 5.1.3 on 2024-12-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodCafe', '0001_initial'),
        ('member', '0003_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('sDate', models.DateTimeField(auto_now=True)),
                ('star_members', models.ManyToManyField(related_name='star_members', to='member.member')),
                ('starred_cafes', models.ManyToManyField(related_name='starred_cafes', to='FoodCafe.cafe')),
                ('starred_foods', models.ManyToManyField(related_name='starred_foods', to='FoodCafe.food')),
            ],
        ),
    ]
