# Generated by Django 5.1.3 on 2024-12-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodCafe', '0002_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='starred_cafes',
        ),
        migrations.RemoveField(
            model_name='star',
            name='starred_foods',
        ),
        migrations.RemoveField(
            model_name='foodinfo',
            name='food',
        ),
        migrations.RemoveField(
            model_name='star',
            name='star_members',
        ),
        migrations.DeleteModel(
            name='Cafeinfo',
        ),
        migrations.DeleteModel(
            name='Cafe',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Foodinfo',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
