# Generated by Django 5.1.3 on 2024-11-25 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nicName', models.CharField(max_length=100)),
                ('tel', models.CharField(default='010-0000-0000', max_length=20)),
                ('gender', models.CharField(default='남자', max_length=10)),
                ('hobby', models.CharField(default='game', max_length=50)),
                ('mdate', models.DateTimeField(default=datetime.datetime(2024, 11, 25, 10, 36, 27, 951643))),
            ],
        ),
    ]
