# Generated by Django 5.1.4 on 2025-01-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0014_alter_fboard_btime_alter_ftime_ftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='bTime',
            field=models.CharField(choices=[(120, '2시간 이상'), (45, '30분~1시간'), (10, '10분 이내'), (30, '30분 이내'), (0, '바로 입장'), (60, '1시간 이상')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ftime',
            name='fTime',
            field=models.IntegerField(choices=[(120, '2시간 이상'), (45, '30분~1시간'), (10, '10분 이내'), (30, '30분 이내'), (0, '바로 입장'), (60, '1시간 이상')]),
        ),
    ]
