# Generated by Django 5.1.4 on 2025-01-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0020_alter_fboard_btime_alter_ftime_ftime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fboard',
            name='pKey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='bTime',
            field=models.CharField(choices=[(0, '바로 입장'), (10, '10분 이내'), (120, '2시간 이상'), (45, '30분~1시간'), (60, '1시간 이상'), (30, '30분 이내')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ftime',
            name='fTime',
            field=models.IntegerField(choices=[(0, '바로 입장'), (10, '10분 이내'), (120, '2시간 이상'), (45, '30분~1시간'), (60, '1시간 이상'), (30, '30분 이내')]),
        ),
    ]
