# Generated by Django 5.1.4 on 2024-12-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cNo', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100)),
                ('cCategory', models.CharField(max_length=100)),
                ('cLocation', models.CharField(max_length=1000)),
                ('cTel', models.CharField(max_length=100)),
                ('cInfo', models.CharField(max_length=100)),
                ('cDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fNo', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100)),
                ('fCategory', models.CharField(max_length=100)),
                ('fLocation', models.CharField(max_length=1000)),
                ('fTel', models.CharField(max_length=100)),
                ('fInfo', models.CharField(max_length=100)),
                ('fDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cafeinfo',
            fields=[
                ('ccNo', models.AutoField(primary_key=True, serialize=False)),
                ('cPark', models.CharField(max_length=200)),
                ('cSub', models.CharField(max_length=200)),
                ('cMenu', models.CharField(max_length=200)),
                ('cPrice', models.CharField(max_length=200)),
                ('ccDate', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodCafe.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Foodinfo',
            fields=[
                ('ffNo', models.AutoField(primary_key=True, serialize=False)),
                ('fPark', models.CharField(max_length=200)),
                ('fSub', models.CharField(max_length=200)),
                ('fMenu', models.CharField(max_length=200)),
                ('fPrice', models.CharField(max_length=200)),
                ('ffDate', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodCafe.food')),
            ],
        ),
    ]
