# Generated by Django 5.1.3 on 2024-12-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_member_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
