# Generated by Django 5.1.3 on 2024-12-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0010_alter_fboard_btime_alter_ftime_ftime'),
        ('member', '0004_delete_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('sDate', models.DateTimeField(auto_now=True)),
                ('fboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_fboard', to='foodBoard.fboard')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_member', to='member.member')),
            ],
        ),
    ]
