# Generated by Django 5.1.3 on 2024-12-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_star_star_star_fboard_star_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='verification_email',
        ),
        migrations.RemoveField(
            model_name='star',
            name='fboard',
        ),
        migrations.RemoveField(
            model_name='star',
            name='member',
        ),
        migrations.AddField(
            model_name='star',
            name='star',
            field=models.ManyToManyField(default='', related_name='star_members', to='member.member'),
        ),
    ]
