# Generated by Django 5.1.3 on 2024-12-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sInput', models.CharField(max_length=200)),
                ('sLocation', models.CharField(max_length=200, null=True)),
                ('sMenu', models.CharField(max_length=200, null=True)),
                ('sKeyword', models.CharField(max_length=200, null=True)),
                ('sName', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
