# Generated by Django 5.1.3 on 2024-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('aId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('aDate', models.DateField(max_length=100)),
                ('aTicket', models.IntegerField(default=0)),
                ('usedTicket', models.IntegerField(default=0)),
            ],
        ),
    ]
