# Generated by Django 5.1.3 on 2024-12-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='aPoint',
            field=models.IntegerField(default=0),
        ),
    ]
