# Generated by Django 5.1.4 on 2024-12-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('웨이팅', '웨이팅👥'), ('감성카페', '감성카페☕'), ('추천맛집', '추천맛집😋'), ('생활/편의', '생활/편의🧼'), ('사건사고', '사건사고😈'), ('취미', '취미🎮'), ('기타', '기타🔍'), ('풍경', '풍경🌴'), ('실시간공유', '실시간공유🗫'), ('교통', '교통🚗')], max_length=500),
        ),
    ]
