# Generated by Django 5.1.3 on 2024-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('교통', '교통🚗'), ('기타', '기타🔍'), ('생활/편의', '생활/편의🧼'), ('풍경', '풍경🌴'), ('취미', '취미🎮'), ('실시간공유', '실시간공유🗫'), ('웨이팅', '웨이팅👥'), ('사건사고', '사건사고😈'), ('추천맛집', '추천맛집😋'), ('감성카페', '감성카페☕')], max_length=500),
        ),
    ]
