# Generated by Django 5.1.3 on 2024-11-25 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 11, 15, 43, 865413)),
        ),
    ]
