# Generated by Django 5.1.4 on 2024-12-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('aNo', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('aDate', models.DateField(max_length=100)),
                ('aTicket', models.IntegerField(default=0)),
                ('usedTicket', models.IntegerField(default=0)),
                ('coupon_code', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_member', to='member.member')),
            ],
        ),
    ]
