# Generated by Django 5.1.3 on 2024-12-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
