# Generated by Django 5.1.3 on 2024-12-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_delete_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
