# Generated by Django 5.1.3 on 2024-12-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0011_alter_ftime_ftime'),
        ('member', '0002_remove_star_star_star_fboard_star_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='food',
        ),
        migrations.AddField(
            model_name='rating',
            name='fboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='foodBoard.fboard'),
            preserve_default=False,
        ),
    ]
