# Generated by Django 5.1.3 on 2024-12-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_rating_food_rating_fboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='cafe',
        ),
    ]
