# Generated by Django 5.1.3 on 2024-12-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodCafe', '0004_initial'),
        ('member', '0003_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rNo', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('rDate', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodCafe.cafe')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodCafe.food')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('sDate', models.DateTimeField(auto_now=True)),
                ('cafe', models.ManyToManyField(related_name='star_cafe', to='FoodCafe.cafe')),
                ('food', models.ManyToManyField(related_name='star_food', to='FoodCafe.food')),
                ('star_members', models.ManyToManyField(related_name='star_members', to='member.member')),
            ],
        ),
    ]
