# Generated by Django 5.1.4 on 2025-01-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('취미', '취미🎮'), ('생활/편의', '생활/편의🧼'), ('감성카페', '감성카페☕'), ('풍경', '풍경🌴'), ('기타', '기타🔍'), ('웨이팅', '웨이팅👥'), ('교통', '교통🚗'), ('사건사고', '사건사고😈'), ('추천맛집', '추천맛집😋'), ('실시간공유', '실시간공유🗫')], max_length=500),
        ),
    ]
