# Generated by Django 5.1.4 on 2025-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('기타', '기타🔍'), ('감성카페', '감성카페☕'), ('생활/편의', '생활/편의🧼'), ('실시간공유', '실시간공유🗫'), ('취미', '취미🎮'), ('웨이팅', '웨이팅👥'), ('풍경', '풍경🌴'), ('추천맛집', '추천맛집😋'), ('교통', '교통🚗'), ('사건사고', '사건사고😈')], max_length=500),
        ),
    ]
