# Generated by Django 5.1.3 on 2025-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='coupon_code',
        ),
    ]
