# Generated by Django 5.1.3 on 2024-12-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bselect',
            field=models.CharField(default='기타', max_length=500),
        ),
        migrations.AlterField(
            model_name='board',
            name='bgps',
            field=models.CharField(max_length=1000),
        ),
    ]
