# Generated by Django 5.1.3 on 2024-12-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_bselect_alter_board_bgps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(max_length=500),
        ),
    ]
