# Generated by Django 5.1.3 on 2024-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_bselect'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like_member',
            field=models.ManyToManyField(default='', related_name='like_member', to='member.member'),
        ),
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('교통', '교통🚗'), ('웨이팅', '웨이팅👥'), ('풍경', '풍경🌴'), ('기타', '기타🔍'), ('취미', '취미🎮'), ('사건사고', '사건사고😈'), ('실시간공유', '실시간공유🗫'), ('생활/편의', '생활/편의🧼'), ('추천맛집', '추천맛집😋'), ('감성카페', '감성카페☕')], max_length=500),
        ),
    ]
