# Generated by Django 5.1.3 on 2024-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('풍경', '풍경🌴'), ('생활/편의', '생활/편의🧼'), ('웨이팅', '웨이팅👥'), ('교통', '교통🚗'), ('추천맛집', '추천맛집😋'), ('취미', '취미🎮'), ('기타', '기타🔍'), ('사건사고', '사건사고😈'), ('감성카페', '감성카페☕'), ('실시간공유', '실시간공유🗫')], max_length=500),
        ),
    ]
