# Generated by Django 5.1.4 on 2024-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_board_bselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bselect',
            field=models.CharField(choices=[('생활/편의', '생활/편의🧼'), ('취미', '취미🎮'), ('웨이팅', '웨이팅👥'), ('추천맛집', '추천맛집😋'), ('실시간공유', '실시간공유🗫'), ('사건사고', '사건사고😈'), ('풍경', '풍경🌴'), ('감성카페', '감성카페☕'), ('기타', '기타🔍'), ('교통', '교통🚗')], max_length=500),
        ),
    ]
