# Generated by Django 5.1.3 on 2024-12-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('used_from', models.DateTimeField()),
                ('used_to', models.DateTimeField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.attendance')),
            ],
        ),
    ]
